export const SAVE_CURRENT_USER = 'SAVE_CURRENT_USER';
export const CHANGE_IS_USER_NAV_LOCKED = 'CHANGE_IS_USER_NAV_LOCKED';
export const CHANGE_IS_USER_NAV_OPENED = 'CHANGE_IS_USER_NAV_OPENED';
export const ADD_TREE_POSTS = 'ADD_TREE_POSTS';
export const ADD_USERS = 'ADD_USERS';